// <auto-generated />
namespace MovieMadness.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removed_some_migration_files : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removed_some_migration_files));
        
        string IMigrationMetadata.Id
        {
            get { return "201504201753539_removed_some_migration_files"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
